theme: jekyll-theme-minimal
title: Isle Royale browse, climate change, and carbon stocks
description: This project explores interactions between climate change, forest dynamics, and moose browsing, to project how carbon stocks might change in the future.
